<a href="https://colab.research.google.com/github/MostafijurNaeem/Python/blob/main/NumPy_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Creating a 1D array
arr1 = np.array([1, 2, 3])
print("1D Array:", arr1)

# Creating a 2D array
arr2 = np.array([[[1, 2], [3, 4]], [[4, 5], [5, 6]]])
print("2D Array:\n", arr2)

1D Array: [1 2 3]
2D Array:
 [[[1 2]
  [3 4]]

 [[4 5]
  [5 6]]]


In [ ]:
# Creating an ndarray
arr = np.array([[[1,2, 3], [2,3, 4]], [[3,4, 5], [4,5, 6]]])
print("Array:\n", arr)

# Properties of ndarray
print("Number of Dimensions:", arr.ndim)
print("Shape of Array:", arr.shape)
print("Data Type:", arr.dtype)


Array:
 [[[1 2 3]
  [2 3 4]]

 [[3 4 5]
  [4 5 6]]]
Number of Dimensions: 3
Shape of Array: (2, 2, 3)
Data Type: int64


In [ ]:
# Array with default integer dtype
arr = np.array([1, 2, 3])
print("Default dtype:", arr.dtype)

# Array with custom dtype
arr_float = np.array([1, 2, 3], dtype="float32")
print("Custom dtype:", arr_float.dtype)

# Complex dtype
arr_complex = np.array([1 + 2j, 3 + 4j])
print("Complex dtype:", arr_complex.dtype)

Default dtype: int64
Custom dtype: float32
Complex dtype: complex128


In [ ]:
arr = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

# Scaler operations
print("Array + 10:", arr + 10)
print("Array * 2:", arr * 2)

# Mathematical operations
print("Sum:", arr.sum())
print("Mean:", arr.mean())
print("Max:", arr.max())

# Element-wise operations
print("Addition:", arr + arr2)
print("Multiplication:", arr * arr2)

Array + 10: [11 12 13 14]
Array * 2: [2 4 6 8]
Sum: 10
Mean: 2.5
Max: 4
Addition: [ 6  8 10 12]
Multiplication: [ 5 12 21 32]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print("Original Array:", arr)

# Accessing elements
print("First Element:", arr[0])
print("Last Element:", arr[-1])

# Slicing
print("First 3 Elements:", arr[1:3])
print("Last 2 Elements:", arr[-2:])

Original Array: [10 20 30 40 50]
First Element: 10
Last Element: 50
First 3 Elements: [20 30]
Last 2 Elements: [40 50]


In [ ]:
arr = np.array([[10, 20],
                [30, 40],
                [50, 60]])

print(arr.ndim)
print(arr.shape)

print("Specific Elements: ", arr[-1])
print("Boolean Masking:", arr[arr > 20])

2
(3, 2)
Specific Elements:  [50 60]
Boolean Masking: [30 40 50 60]


In [ ]:
nums = np.arange(1, 11)

mult_nums = nums * 3

print(mult_nums.mean())
print(mult_nums.max())

16.5
30


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Row-wise iteration
for row in arr:
    print("Row:", row)

# Element-wise iteration
for element in np.nditer(arr):
    print("Element:", element)

Row: [1 2 3]
Row: [4 5 6]
Element: 1
Element: 2
Element: 3
Element: 4
Element: 5
Element: 6


In [ ]:
arr1 = np.array([[1, 2], [3, 4]], dtype="float64")
arr2 = np.array([[5, 6], [7, 8]], dtype="float64")

print("Arr 1\n",arr1)
print("Arr 2\n",arr2)

print("Dot\n",np.dot(arr1, arr2))

print("Transpose\n",arr1.T)

round(np.linalg.det(arr1), 3)

Arr 1
 [[1. 2.]
 [3. 4.]]
Arr 2
 [[5. 6.]
 [7. 8.]]
Dot
 [[19. 22.]
 [43. 50.]]
Transpose
 [[1. 3.]
 [2. 4.]]


-2.0

In [ ]:
# Dot product
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print("Dot Product:\n", np.dot(arr1, arr2))

# Transpose of a matrix
print("Transpose:\n", arr1.T)

# Determinant
print("Determinant:", np.linalg.det(arr1))

Dot Product:
 [[19 22]
 [43 50]]
Transpose:
 [[1 3]
 [2 4]]
Determinant: -2.0000000000000004


In [ ]:
arr = np.array([3, 1, 4, 1, 5, 9])

# Sorting
print("Sorted Array:", np.sort(arr))

# Searching
print("Index of 1:", np.where(arr == 1))

# Counting
print("Count of 1s:", np.count_nonzero(arr == 1))

Sorted Array: [1 1 3 4 5 9]
Index of 1: (array([1, 3]),)
Count of 1s: 2


In [ ]:
rand_arr = np.random.randint(1, 51, size=(3,3))

print("Random Array\n", rand_arr)
print("Mean", rand_arr.mean())
print("Transpose\n", rand_arr.T)
print("Sorted along Rows\n", np.sort(rand_arr, axis=1))
print("Elements greater than 25\n", rand_arr[rand_arr > 25])
print(np.dot(rand_arr, rand_arr.T))

Random Array
 [[15 34 36]
 [19 13 18]
 [ 4 33 13]]
Mean 20.555555555555557
Transpose
 [[15 19  4]
 [34 13 33]
 [36 18 13]]
Sorted along Rows
 [[15 34 36]
 [13 18 19]
 [ 4 13 33]]
Elements greater than 25
 [34 36 33]
[[2677 1375 1650]
 [1375  854  739]
 [1650  739 1274]]
