<a href="https://colab.research.google.com/github/MostafijurNaeem/Python/blob/main/PP_o2_25(Md_Mostafijur_Rahman_Naeem).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question - 1:


In [29]:
Employee_score = input("Please input your score : ")
Employee_score = int(Employee_score)

if Employee_score >= 90:
    print("Your grade is  e xcellent")
elif Employee_score >= 80:
    print("Your grade is Very Good")
elif Employee_score >= 70:
    print("Your grade is Good")
elif Employee_score >= 60:
    print("Your grade is Satisfactory")
else:
    print("Your grade Needs Improvement")


Please input your score : 85
Your grade is Very Good


Problem - 2


In [30]:
n = int(input("Enter a number: "))
sum_of_odds = 0
i = 1

while i <= n:
  if i % 2 != 0:
    sum_of_odds += i
  i += 1

print("The sum of all odd numbers between 1 and", n, "is:\n", sum_of_odds)

Enter a number: 100
The sum of all odd numbers between 1 and 100 is:
 2500


Problem -3


In [31]:
#a.
# re paackage must be imported when working regular expression in python.

#b.
import re
x = "banana"
matches = re.finditer("a", x)

positions = [match.start() for match in matches]
print(f'The positions of "a" in x are: {positions}\n')

# c. Replacing "what" with "where" in the string y
y = "Life is what happens when you're busy making other plans"
new_y = re.sub(r"\bwhat\b", "where", y)
print(new_y)


The positions of "a" in x are: [1, 3, 5]

Life is where happens when you're busy making other plans


Problem - 4


In [32]:
#a. Create and open the file in write mode

with open("notes.txt", "w") as file:
    pass

#b. Append a line to the file
with open("notes.txt", "a") as file:
    file.write("programming is an essential skill in today's world.\n")

# Read and print the contents of the file
with open("notes.txt", "r") as file:
    contents = file.read()
    print(contents)

#c. Check if the file exists, and delete it if so
import os
if os.path.exists("notes.txt"):
    os.remove("notes.txt")
    print("File deleted successfully.")
else:
    print("File does not exist!")


programming is an essential skill in today's world.

File deleted successfully.


problem - 5


In [33]:
# a. Create a 2D array (3x3) with random integers between 5 and 15
import numpy as np
array_2d = np.random.randint(5, 16, size=(3, 3))

# b. Display the array and find its transpose
print("Original Array:")
print(array_2d)

print("\nTranspose of the Array:")
transpose_array = array_2d.T
print(transpose_array)

# c. Calculate the sum of all elements in the array
sum_of_elements = np.sum(array_2d)
print("\nSum of all elements:", sum_of_elements)

# Find the indices of elements that are greater than 10
indices = np.where(array_2d > 10)
print("\nIndices of elements greater than 10:")
print(list(zip(indices[0], indices[1])))

Original Array:
[[13 15 13]
 [ 7  6  8]
 [14  8 13]]

Transpose of the Array:
[[13  7 14]
 [15  6  8]
 [13  8 13]]

Sum of all elements: 97

Indices of elements greater than 10:
[(0, 0), (0, 1), (0, 2), (2, 0), (2, 2)]
